"""Melee damage and accuracy tests for Noxious-haleberd-based setups."""

import unittest

from combat_engine.Domain.Loadout import Loadout
from combat_engine.Data.Registries.WeaponRegistry import WeaponRegistry
from combat_engine.Data.Registries.PrayerRegistry import PrayerRegistry
from combat_engine.Data.Registries.PotionRegistry import PotionRegistry

SETUPS = [
    {
        "name": "TOO_setup",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 40826,
        "expected_max_hit": 66,
    },
    {
        "name": "OOO_oathplate_helm",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42316,
        "expected_max_hit": 66,
    },
    {
        "name": "TOO_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 40379,
        "expected_max_hit": 65,
    },
    {
        "name": "TOO_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34524,
        "expected_max_hit": 55,
    },
    {
        "name": "TOO_accurate_style",
        "prayer": "piety",
        "boosts": ["super combat"],
        "attack_style_override": "Accurate",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 41648,
        "expected_max_hit": 65,
    },
    {
        "name": "TOO_no_supercombat",
        "prayer": "piety",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34524,
        "expected_max_hit": 56,
    },
    {
        "name": "TOO_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29318,
        "expected_max_hit": 47,
    },
    {
        "name": "TTT_torva_body_legs",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 67,
    },
    {
        "name": "TOO_bandos_no_neck",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'bandos chestplate', 'oathplate legs', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34717,
        "expected_max_hit": 63,
    },
    {
        "name": "TOO_bandos_no_neck_no_gloves",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'bandos chestplate', 'oathplate legs', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32333,
        "expected_max_hit": 60,
    },
    {
        "name": "OOO_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 45147,
        "expected_max_hit": 67,
    },
    {
        "name": "OOO_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 44402,
        "expected_max_hit": 67,
    },
    {
        "name": "OOO_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of strength', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42912,
        "expected_max_hit": 67,
    },
    {
        "name": "OOO_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 46637,
        "expected_max_hit": 67,
    },
    {
        "name": "OOO_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 46190,
        "expected_max_hit": 68,
    },
    {
        "name": "OOO_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 44759,
        "expected_max_hit": 65,
    },
    {
        "name": "OOO_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 39438,
        "expected_max_hit": 63,
    },
    {
        "name": "OOO_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 41003,
        "expected_max_hit": 58,
    },
    {
        "name": "OOO_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 51645,
        "expected_max_hit": 75,
    },
    {
        "name": "OOO_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42568,
        "expected_max_hit": 62,
    },
    {
        "name": "OOO_super_attack",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK", "SUPER_STRENGTH"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 46637,
        "expected_max_hit": 68,
    },
    {
        "name": "OOO_chivalry_zamorak",
        "prayer": "chivalry",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 49454,
        "expected_max_hit": 72,
    },
    {
        "name": "OOO_no_piety_ancient",
        "prayer": "none",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35995,
        "expected_max_hit": 51,
    },
    {
        "name": "OOO_burst_strength_no_pot",
        "prayer": "BURST_OF_STRENGTH",
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34743,
        "expected_max_hit": 50,
    },
    {
        "name": "OOO_accurate_style",
        "prayer": "piety",
        "boosts": ["super combat"],
        "attack_style_override": "Accurate",
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 47576,
        "expected_max_hit": 66,
    },
    {
        "name": "OOO_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'fire cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 46190,
        "expected_max_hit": 67,
    },
    {
        "name": "OOO_no_defender",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42316,
        "expected_max_hit": 66,
    },
    {
        "name": "OOO_salve",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'salve', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42912,
        "expected_max_hit": 65,
    },
    {
        "name": "OOO_torture_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'berserker ring (i)', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 44700,
        "expected_max_hit": 66,
    },
    {
        "name": "OOO_fury_bandos",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'bandos chestplate', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42018,
        "expected_max_hit": 67,
    },
    {
        "name": "TOO_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 43657,
        "expected_max_hit": 68,
    },
    {
        "name": "TOO_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 42912,
        "expected_max_hit": 67,
    },
    {
        "name": "TOO_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of strength', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 41422,
        "expected_max_hit": 68,
    },
    {
        "name": "TOO_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 45147,
        "expected_max_hit": 67,
    },
    {
        "name": "TOO_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 44700,
        "expected_max_hit": 68,
    },
    {
        "name": "TOO_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 49995,
        "expected_max_hit": 75,
    },
    {
        "name": "TOO_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 41208,
        "expected_max_hit": 62,
    },
    {
        "name": "TOO_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 43329,
        "expected_max_hit": 66,
    },
    {
        "name": "TOO_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 38178,
        "expected_max_hit": 64,
    },
    {
        "name": "only_scythe",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": [],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 50,
    },
    {
        "name": "only_ultor",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['ultor ring'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 53,
    },
    {
        "name": "only_amulet_of_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31439,
        "expected_max_hit": 53,
    },
    {
        "name": "only_berserker_ring_i",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 52,
    },
    {
        "name": "only_primordial_boots",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29502,
        "expected_max_hit": 51,
    },
    {
        "name": "only_amulet_of_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30694,
        "expected_max_hit": 52,
    },
    {
        "name": "only_amulet_of_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 53,
    },
    {
        "name": "only_torture_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31439,
        "expected_max_hit": 55,
    },
    {
        "name": "only_torture_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31737,
        "expected_max_hit": 54,
    },
    {
        "name": "only_fury_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30694,
        "expected_max_hit": 54,
    },
    {
        "name": "only_fury_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30992,
        "expected_max_hit": 53,
    },
    {
        "name": "only_strength_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 55,
    },
    {
        "name": "only_torture_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'ferocious gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33823,
        "expected_max_hit": 56,
    },
    {
        "name": "only_fury_infernal",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31290,
        "expected_max_hit": 54,
    },
    {
        "name": "only_bring_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)', 'ferocious gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31588,
        "expected_max_hit": 56,
    },
    {
        "name": "only_prims_rancour",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots', 'amulet of rancour'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33227,
        "expected_max_hit": 54,
    },
    {
        "name": "only_torture_infernal",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32035,
        "expected_max_hit": 55,
    },
    {
        "name": "only_torture_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31737,
        "expected_max_hit": 56,
    },
    {
        "name": "only_fury_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'berserker ring (i)', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30992,
        "expected_max_hit": 55,
    },
    {
        "name": "only_torture_bring_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 26586,
        "expected_max_hit": 45,
    },
    {
        "name": "only_fury_bring_no_scb",
        "prayer": "piety",
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 25956,
        "expected_max_hit": 46,
    },
    {
        "name": "TTT_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 67,
    },
    {
        "name": "TTT_super_atk_str",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK", "SUPER_STRENGTH"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 67,
    },
    {
        "name": "TTT_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 40590,
        "expected_max_hit": 74,
    },
    {
        "name": "TTT_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33456,
        "expected_max_hit": 61,
    },
    {
        "name": "TTT_attack_potion",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 57,
    },
    {
        "name": "TTT_super_attack_only",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 57,
    },
    {
        "name": "TTT_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35178,
        "expected_max_hit": 65,
    },
    {
        "name": "TTT_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30996,
        "expected_max_hit": 63,
    },
    {
        "name": "TTT_incredible_reflexes",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35178,
        "expected_max_hit": 56,
    },
    {
        "name": "TTT_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32226,
        "expected_max_hit": 58,
    },
    {
        "name": "TTT_supernatural_strength",
        "prayer": "SUPERNATURAL_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30996,
        "expected_max_hit": 60,
    },
    {
        "name": "TTT_clarity_of_thought",
        "prayer": "CLARITY_OF_THOUGHT",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32226,
        "expected_max_hit": 56,
    },
    {
        "name": "TTT_improved_reflexes",
        "prayer": "IMPROVED_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33702,
        "expected_max_hit": 56,
    },
    {
        "name": "TTT_chivalry_supercombat",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35178,
        "expected_max_hit": 65,
    },
    {
        "name": "TTT_ultimate_strength_scb",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30996,
        "expected_max_hit": 63,
    },
    {
        "name": "TTT_burst_strength_no_pot",
        "prayer": "BURST_OF_STRENGTH",
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 27306,
        "expected_max_hit": 49,
    },
    {
        "name": "TTT_incredible_reflexes_zammy",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 38868,
        "expected_max_hit": 61,
    },
    {
        "name": "TTT_no_piety_ancient_brew",
        "prayer": "none",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 28290,
        "expected_max_hit": 51,
    },
    {
        "name": "TTT_chivalry_ancient_brew",
        "prayer": "chivalry",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32226,
        "expected_max_hit": 59,
    },
    {
        "name": "only_torture_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31439,
        "expected_max_hit": 53,
    },
    {
        "name": "only_fury_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['amulet of fury'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 28016,
        "expected_max_hit": 47,
    },
    {
        "name": "only_strength_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['amulet of strength'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32340,
        "expected_max_hit": 58,
    },
    {
        "name": "only_bring_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32340,
        "expected_max_hit": 58,
    },
    {
        "name": "only_prims_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29502,
        "expected_max_hit": 51,
    },
    {
        "name": "only_torture_piety",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31439,
        "expected_max_hit": 53,
    },
    {
        "name": "only_fury_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29458,
        "expected_max_hit": 50,
    },
    {
        "name": "only_strength_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 24696,
        "expected_max_hit": 49,
    },
    {
        "name": "only_bring_incredible_reflexes",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 28028,
        "expected_max_hit": 43,
    },
    {
        "name": "only_prims_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 25938,
        "expected_max_hit": 44,
    },
    {
        "name": "only_torture_bring_chivalry_scb",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30173,
        "expected_max_hit": 53,
    },
    {
        "name": "only_fury_prims_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30992,
        "expected_max_hit": 53,
    },
    {
        "name": "only_torture_prims_piety_scb",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'primordial boots'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31737,
        "expected_max_hit": 54,
    },
    {
        "name": "only_fury_bring_no_piety_zammy",
        "prayer": "none",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 28634,
        "expected_max_hit": 49,
    },
    {
        "name": "only_strength_bring_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength', 'berserker ring (i)'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29204,
        "expected_max_hit": 55,
    },
    {
        "name": "only_torture_ferocious_chivalry_scb",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'ferocious gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32461,
        "expected_max_hit": 54,
    },
    {
        "name": "only_fury_infernal_ultimate_strength_scb",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 26460,
        "expected_max_hit": 51,
    },
    {
        "name": "only_bring_ferocious_piety_scb",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)', 'ferocious gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31588,
        "expected_max_hit": 56,
    },
    {
        "name": "only_prims_rancour_no_piety_zammy",
        "prayer": "none",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['primordial boots', 'amulet of rancour'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30997,
        "expected_max_hit": 49,
    },
    {
        "name": "only_torture_infernal_burst_strength_scb",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 28165,
        "expected_max_hit": 47,
    },
    {
        "name": "only_avernic_treads",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['avernic treads'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 29949,
        "expected_max_hit": 52,
    },
    {
        "name": "only_ferocious_gloves",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['ferocious gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31588,
        "expected_max_hit": 54,
    },
    {
        "name": "VVV_nothing_else",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31948,
        "expected_max_hit": 55,
    },
    {
        "name": "VVV_cape_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32600,
        "expected_max_hit": 57,
    },
    {
        "name": "VVV_neck_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36023,
        "expected_max_hit": 58,
    },
    {
        "name": "VVV_ring_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'ultor ring'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31948,
        "expected_max_hit": 58,
    },
    {
        "name": "VVV_boots_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'avernic treads'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 32763,
        "expected_max_hit": 57,
    },
    {
        "name": "VVV_nothing_no_scb",
        "prayer": "piety",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 27048,
        "expected_max_hit": 47,
    },
    {
        "name": "VVV_nothing_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 27048,
        "expected_max_hit": 45,
    },
    {
        "name": "VVV_nothing_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 22932,
        "expected_max_hit": 39,
    },
    {
        "name": "VVV_setup",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37490,
        "expected_max_hit": 65,
    },
    {
        "name": "VVV_setup_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36110,
        "expected_max_hit": 63,
    },
    {
        "name": "VVV_setup_ult_str",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31740,
        "expected_max_hit": 61,
    },
    {
        "name": "VVV_setup_super_str",
        "prayer": "SUPERNATURAL_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31740,
        "expected_max_hit": 59,
    },
    {
        "name": "VVV_setup_burst_str",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33120,
        "expected_max_hit": 56,
    },
    {
        "name": "VVV_setup_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31740,
        "expected_max_hit": 54,
    },
    {
        "name": "VVV_setup_no_scb",
        "prayer": "piety",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 31740,
        "expected_max_hit": 55,
    },
    {
        "name": "VVV_setup_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 26910,
        "expected_max_hit": 46,
    },
    {
        "name": "VVV_setup_zammy",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 41630,
        "expected_max_hit": 72,
    },
    {
        "name": "VVV_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35860,
        "expected_max_hit": 65,
    },
    {
        "name": "VVV_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35045,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_strength_ammy",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of strength', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 33415,
        "expected_max_hit": 65,
    },
    {
        "name": "VVV_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37490,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37001,
        "expected_max_hit": 65,
    },
    {
        "name": "VVV_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37001,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 36654,
        "expected_max_hit": 63,
    },
    {
        "name": "VVV_torture_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35371,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_torture_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35371,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_torture_prims_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'primordial boots', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34882,
        "expected_max_hit": 63,
    },
    {
        "name": "VVV_fury_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34556,
        "expected_max_hit": 63,
    },
    {
        "name": "VVV_fury_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34556,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_bring_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37001,
        "expected_max_hit": 63,
    },
    {
        "name": "VVV_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'primordial boots', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 37001,
        "expected_max_hit": 64,
    },
    {
        "name": "VVV_torture_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 35164,
        "expected_max_hit": 62,
    },
    {
        "name": "VVV_torture_ferocious_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34717,
        "expected_max_hit": 61,
    },
    {
        "name": "VVV_torture_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 34540,
        "expected_max_hit": 62,
    },
    {
        "name": "VVV_torture_ult_str",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "noxious haleberd",
        "expected_accuracy_roll": 30360,
        "expected_max_hit": 61,
    },
]


def _make_test_classes():
    """Create one TestCase subclass per setup."""

    for setup in SETUPS:
        setup_name = setup["name"]
        class_name = f"{setup_name}"

        def build_accuracy_test(setup=setup):
            def test(self):
                player = _build_player_from_setup(setup)
                player.calc_all_the_things(combat_style="Melee", attack_type="Slash")
                self.assertEqual(
                    player.attack_roll, setup["expected_accuracy_roll"],
                    rf"\n setup={setup['name']!r}"
                    rf"\n expected_accuracy_roll={setup['expected_accuracy_roll']}"
                    rf"\n actual_accuracy_roll={{player.attack_roll}}"
                )
            return test

        def build_max_hit_test(setup=setup):
            def test(self):
                player = _build_player_from_setup(setup)
                player.calc_all_the_things(combat_style="Melee", attack_type="Slash")
                self.assertEqual(
                    player.max_hit, setup["expected_max_hit"],
                    rf"\n setup={setup['name']!r}"
                    rf"\n expected_max_hit={setup['expected_max_hit']}"
                    rf"\n actual_max_hit={{player.max_hit}}"
                )
            return test

        TestCls = type(class_name, (unittest.TestCase,), {
            "test_accuracy_roll": build_accuracy_test(setup),
            "test_max_hit":      build_max_hit_test(setup),
        })
        globals()[class_name] = TestCls


def _build_player_from_setup(setup):
    player = Loadout(gear_names=setup["gear_names"]).build()

    weapon = WeaponRegistry.get(setup["weapon"])
    player.equip_weapon(weapon)

    if "attack_style_override" in setup:
        player.weapon.attack_style = setup["attack_style_override"]

    if "prayer" in setup:
        player.prayer = PrayerRegistry.get(setup["prayer"])

    if "boosts" in setup:
        player.boosts = [PotionRegistry.get(b) for b in setup["boosts"]]

    return player


_make_test_classes()


if __name__ == "__main__":
    unittest.main()
