"""Melee damage and accuracy tests for Fists-based setups."""

import unittest

from CombatSim.CombatEngine.Domain.Loadout import Loadout
from CombatSim.CombatEngine.Data.Registries.WeaponRegistry import WeaponRegistry
from CombatSim.CombatEngine.Data.Registries.PrayerRegistry import PrayerRegistry
from CombatSim.CombatEngine.Data.Registries.PotionRegistry import PotionRegistry

SETUPS = [
    {
        "name": "TOO_setup",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 32,
    },
    {
        "name": "OOO_oathplate_helm",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 31,
    },
    {
        "name": "TOO_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16539,
        "expected_max_hit": 31,
    },
    {
        "name": "TOO_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14364,
        "expected_max_hit": 26,
    },
    {
        "name": "TOO_accurate_style",
        "prayer": "piety",
        "boosts": ["super combat"],
        "attack_style_override": "Accurate",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17328,
        "expected_max_hit": 31,
    },
    {
        "name": "TOO_no_supercombat",
        "prayer": "piety",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14364,
        "expected_max_hit": 27,
    },
    {
        "name": "TOO_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12198,
        "expected_max_hit": 22,
    },
    {
        "name": "TTT_torva_body_legs",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_bandos_no_neck",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'bandos chestplate', 'oathplate legs', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13261,
        "expected_max_hit": 29,
    },
    {
        "name": "TOO_bandos_no_neck_no_gloves",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'bandos chestplate', 'oathplate legs', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10877,
        "expected_max_hit": 25,
    },
    {
        "name": "OOO_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 19668,
        "expected_max_hit": 33,
    },
    {
        "name": "OOO_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18923,
        "expected_max_hit": 32,
    },
    {
        "name": "OOO_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of strength', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17433,
        "expected_max_hit": 33,
    },
    {
        "name": "OOO_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 21158,
        "expected_max_hit": 32,
    },
    {
        "name": "OOO_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 20711,
        "expected_max_hit": 33,
    },
    {
        "name": "OOO_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 20306,
        "expected_max_hit": 32,
    },
    {
        "name": "OOO_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17892,
        "expected_max_hit": 31,
    },
    {
        "name": "OOO_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18602,
        "expected_max_hit": 28,
    },
    {
        "name": "OOO_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 23430,
        "expected_max_hit": 37,
    },
    {
        "name": "OOO_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 19312,
        "expected_max_hit": 30,
    },
    {
        "name": "OOO_super_attack",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK", "SUPER_STRENGTH"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 21158,
        "expected_max_hit": 33,
    },
    {
        "name": "OOO_chivalry_zamorak",
        "prayer": "chivalry",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 22436,
        "expected_max_hit": 35,
    },
    {
        "name": "OOO_no_piety_ancient",
        "prayer": "none",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16330,
        "expected_max_hit": 25,
    },
    {
        "name": "OOO_burst_strength_no_pot",
        "prayer": "BURST_OF_STRENGTH",
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15762,
        "expected_max_hit": 24,
    },
    {
        "name": "OOO_accurate_style",
        "prayer": "piety",
        "boosts": ["super combat"],
        "attack_style_override": "Accurate",
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 21584,
        "expected_max_hit": 33,
    },
    {
        "name": "OOO_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'fire cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 20711,
        "expected_max_hit": 32,
    },
    {
        "name": "OOO_no_defender",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 31,
    },
    {
        "name": "OOO_salve",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'salve', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17433,
        "expected_max_hit": 30,
    },
    {
        "name": "OOO_torture_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'berserker ring (i)', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 19221,
        "expected_max_hit": 31,
    },
    {
        "name": "OOO_fury_bandos",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['oathplate helm', 'bandos chestplate', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18923,
        "expected_max_hit": 32,
    },
    {
        "name": "TOO_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of torture', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 19668,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of fury', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18923,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of strength', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17433,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 21158,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'primordial boots', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 20711,
        "expected_max_hit": 33,
    },
    {
        "name": "TOO_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 23430,
        "expected_max_hit": 37,
    },
    {
        "name": "TOO_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 19312,
        "expected_max_hit": 31,
    },
    {
        "name": "TOO_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 20306,
        "expected_max_hit": 32,
    },
    {
        "name": "TOO_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'oathplate body', 'oathplate legs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape', 'avernic defender'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17892,
        "expected_max_hit": 31,
    },
    {
        "name": "only_scythe",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": [],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 16,
    },
    {
        "name": "only_ultor",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['ultor ring'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 19,
    },
    {
        "name": "only_amulet_of_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11771,
        "expected_max_hit": 18,
    },
    {
        "name": "only_berserker_ring_i",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 18,
    },
    {
        "name": "only_primordial_boots",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9834,
        "expected_max_hit": 17,
    },
    {
        "name": "only_amulet_of_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11026,
        "expected_max_hit": 18,
    },
    {
        "name": "only_amulet_of_strength",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 18,
    },
    {
        "name": "only_torture_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11771,
        "expected_max_hit": 20,
    },
    {
        "name": "only_torture_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12069,
        "expected_max_hit": 19,
    },
    {
        "name": "only_fury_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11026,
        "expected_max_hit": 20,
    },
    {
        "name": "only_fury_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11324,
        "expected_max_hit": 19,
    },
    {
        "name": "only_strength_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 20,
    },
    {
        "name": "only_torture_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'ferocious gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14155,
        "expected_max_hit": 21,
    },
    {
        "name": "only_fury_infernal",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11622,
        "expected_max_hit": 20,
    },
    {
        "name": "only_bring_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)', 'ferocious gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11920,
        "expected_max_hit": 21,
    },
    {
        "name": "only_prims_rancour",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots', 'amulet of rancour'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13559,
        "expected_max_hit": 20,
    },
    {
        "name": "only_torture_infernal",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12367,
        "expected_max_hit": 20,
    },
    {
        "name": "only_torture_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12069,
        "expected_max_hit": 21,
    },
    {
        "name": "only_fury_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'berserker ring (i)', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11324,
        "expected_max_hit": 21,
    },
    {
        "name": "only_torture_bring_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9954,
        "expected_max_hit": 17,
    },
    {
        "name": "only_fury_bring_no_scb",
        "prayer": "piety",
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9324,
        "expected_max_hit": 17,
    },
    {
        "name": "TTT_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 33,
    },
    {
        "name": "TTT_super_atk_str",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK", "SUPER_STRENGTH"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 33,
    },
    {
        "name": "TTT_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18810,
        "expected_max_hit": 36,
    },
    {
        "name": "TTT_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15504,
        "expected_max_hit": 30,
    },
    {
        "name": "TTT_attack_potion",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 28,
    },
    {
        "name": "TTT_super_attack_only",
        "prayer": "piety",
        "boosts": ["SUPER_ATTACK"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 28,
    },
    {
        "name": "TTT_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16302,
        "expected_max_hit": 31,
    },
    {
        "name": "TTT_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14364,
        "expected_max_hit": 31,
    },
    {
        "name": "TTT_incredible_reflexes",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16302,
        "expected_max_hit": 27,
    },
    {
        "name": "TTT_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14934,
        "expected_max_hit": 28,
    },
    {
        "name": "TTT_supernatural_strength",
        "prayer": "SUPERNATURAL_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14364,
        "expected_max_hit": 29,
    },
    {
        "name": "TTT_clarity_of_thought",
        "prayer": "CLARITY_OF_THOUGHT",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14934,
        "expected_max_hit": 27,
    },
    {
        "name": "TTT_improved_reflexes",
        "prayer": "IMPROVED_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15618,
        "expected_max_hit": 27,
    },
    {
        "name": "TTT_chivalry_supercombat",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16302,
        "expected_max_hit": 31,
    },
    {
        "name": "TTT_ultimate_strength_scb",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14364,
        "expected_max_hit": 31,
    },
    {
        "name": "TTT_burst_strength_no_pot",
        "prayer": "BURST_OF_STRENGTH",
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12654,
        "expected_max_hit": 24,
    },
    {
        "name": "TTT_incredible_reflexes_zammy",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 18012,
        "expected_max_hit": 30,
    },
    {
        "name": "TTT_no_piety_ancient_brew",
        "prayer": "none",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13110,
        "expected_max_hit": 25,
    },
    {
        "name": "TTT_chivalry_ancient_brew",
        "prayer": "chivalry",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['torva full helm', 'torva platebody', 'torva platelegs', 'amulet of rancour', 'ultor ring', 'avernic treads', 'ferocious gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14934,
        "expected_max_hit": 29,
    },
    {
        "name": "only_torture_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11771,
        "expected_max_hit": 18,
    },
    {
        "name": "only_fury_ancient_brew",
        "prayer": "piety",
        "boosts": ["super combat", "ancient brew"],
        "gear_names": ['amulet of fury'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10064,
        "expected_max_hit": 16,
    },
    {
        "name": "only_strength_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['amulet of strength'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10560,
        "expected_max_hit": 20,
    },
    {
        "name": "only_bring_zamorak_brew",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10560,
        "expected_max_hit": 19,
    },
    {
        "name": "only_prims_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9834,
        "expected_max_hit": 17,
    },
    {
        "name": "only_torture_piety",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11771,
        "expected_max_hit": 18,
    },
    {
        "name": "only_fury_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10582,
        "expected_max_hit": 17,
    },
    {
        "name": "only_strength_ultimate_strength",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength'],
        "weapon": "Fists",
        "expected_accuracy_roll": 8064,
        "expected_max_hit": 17,
    },
    {
        "name": "only_bring_incredible_reflexes",
        "prayer": "INCREDIBLE_REFLEXES",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9152,
        "expected_max_hit": 15,
    },
    {
        "name": "only_prims_burst_of_strength",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 8646,
        "expected_max_hit": 14,
    },
    {
        "name": "only_torture_bring_chivalry_scb",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11297,
        "expected_max_hit": 19,
    },
    {
        "name": "only_fury_prims_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11324,
        "expected_max_hit": 19,
    },
    {
        "name": "only_torture_prims_piety_scb",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'primordial boots'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12069,
        "expected_max_hit": 19,
    },
    {
        "name": "only_fury_bring_no_piety_zammy",
        "prayer": "none",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['amulet of fury', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10286,
        "expected_max_hit": 18,
    },
    {
        "name": "only_strength_bring_super_combat",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['amulet of strength', 'berserker ring (i)'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9536,
        "expected_max_hit": 20,
    },
    {
        "name": "only_torture_ferocious_chivalry_scb",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'ferocious gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13585,
        "expected_max_hit": 21,
    },
    {
        "name": "only_fury_infernal_ultimate_strength_scb",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['amulet of fury', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 9828,
        "expected_max_hit": 18,
    },
    {
        "name": "only_bring_ferocious_piety_scb",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['berserker ring (i)', 'ferocious gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11920,
        "expected_max_hit": 21,
    },
    {
        "name": "only_prims_rancour_no_piety_zammy",
        "prayer": "none",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['primordial boots', 'amulet of rancour'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12649,
        "expected_max_hit": 18,
    },
    {
        "name": "only_torture_infernal_burst_strength_scb",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['amulet of torture', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10873,
        "expected_max_hit": 17,
    },
    {
        "name": "only_avernic_treads",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['avernic treads'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10281,
        "expected_max_hit": 17,
    },
    {
        "name": "only_ferocious_gloves",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['ferocious gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11920,
        "expected_max_hit": 19,
    },
    {
        "name": "VVV_nothing_else",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10432,
        "expected_max_hit": 17,
    },
    {
        "name": "VVV_cape_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11084,
        "expected_max_hit": 19,
    },
    {
        "name": "VVV_neck_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14507,
        "expected_max_hit": 20,
    },
    {
        "name": "VVV_ring_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'ultor ring'],
        "weapon": "Fists",
        "expected_accuracy_roll": 10432,
        "expected_max_hit": 20,
    },
    {
        "name": "VVV_boots_only",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'avernic treads'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11247,
        "expected_max_hit": 19,
    },
    {
        "name": "VVV_nothing_no_scb",
        "prayer": "piety",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 8832,
        "expected_max_hit": 15,
    },
    {
        "name": "VVV_nothing_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 8832,
        "expected_max_hit": 14,
    },
    {
        "name": "VVV_nothing_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves'],
        "weapon": "Fists",
        "expected_accuracy_roll": 7488,
        "expected_max_hit": 12,
    },
    {
        "name": "VVV_setup",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15974,
        "expected_max_hit": 27,
    },
    {
        "name": "VVV_setup_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15386,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_setup_ult_str",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13524,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_setup_super_str",
        "prayer": "SUPERNATURAL_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13524,
        "expected_max_hit": 25,
    },
    {
        "name": "VVV_setup_burst_str",
        "prayer": "BURST_OF_STRENGTH",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14112,
        "expected_max_hit": 23,
    },
    {
        "name": "VVV_setup_no_piety",
        "prayer": "none",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13524,
        "expected_max_hit": 22,
    },
    {
        "name": "VVV_setup_no_scb",
        "prayer": "piety",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13524,
        "expected_max_hit": 23,
    },
    {
        "name": "VVV_setup_no_scb_no_piety",
        "prayer": "none",
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11466,
        "expected_max_hit": 19,
    },
    {
        "name": "VVV_setup_zammy",
        "prayer": "piety",
        "boosts": ["super combat", "zamorak brew"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 17738,
        "expected_max_hit": 30,
    },
    {
        "name": "VVV_torture",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 14344,
        "expected_max_hit": 27,
    },
    {
        "name": "VVV_fury",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13529,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_strength_ammy",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of strength', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 11899,
        "expected_max_hit": 27,
    },
    {
        "name": "VVV_bring",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15974,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15485,
        "expected_max_hit": 27,
    },
    {
        "name": "VVV_fire_cape",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15485,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of rancour', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 16986,
        "expected_max_hit": 28,
    },
    {
        "name": "VVV_torture_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13855,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_torture_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13855,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_torture_prims_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'primordial boots', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13366,
        "expected_max_hit": 25,
    },
    {
        "name": "VVV_fury_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13040,
        "expected_max_hit": 25,
    },
    {
        "name": "VVV_fury_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of fury', 'ultor ring', 'primordial boots', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13040,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_bring_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'avernic treads', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15485,
        "expected_max_hit": 25,
    },
    {
        "name": "VVV_bring_prims",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of rancour', 'berserker ring (i)', 'primordial boots', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15485,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_torture_ferocious",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15496,
        "expected_max_hit": 28,
    },
    {
        "name": "VVV_torture_ferocious_fire",
        "prayer": "piety",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'ferocious gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'fire cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 15049,
        "expected_max_hit": 27,
    },
    {
        "name": "VVV_torture_chivalry",
        "prayer": "chivalry",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 13816,
        "expected_max_hit": 26,
    },
    {
        "name": "VVV_torture_ult_str",
        "prayer": "ultimate strength",
        "boosts": ["super combat"],
        "gear_names": ['void melee helm', 'elite void top', 'elite void robe', 'void knight gloves', 'amulet of torture', 'ultor ring', 'avernic treads', 'infernal cape'],
        "weapon": "Fists",
        "expected_accuracy_roll": 12144,
        "expected_max_hit": 25,
    },
]


def _make_test_classes():
    """Create one TestCase subclass per setup."""

    for setup in SETUPS:
        setup_name = setup["name"]
        class_name = f"{setup_name}"

        def build_accuracy_test(setup=setup):
            def test(self):
                player = _build_player_from_setup(setup)
                player.calc_all_the_things(combat_style="Melee", attack_type="Crush")
                self.assertEqual(
                    player.attack_roll, setup["expected_accuracy_roll"],
                    rf"\n setup={setup['name']!r}"
                    rf"\n expected_accuracy_roll={setup['expected_accuracy_roll']}"
                    rf"\n actual_accuracy_roll={{player.attack_roll}}"
                )
            return test

        def build_max_hit_test(setup=setup):
            def test(self):
                player = _build_player_from_setup(setup)
                player.calc_all_the_things(combat_style="Melee", attack_type="Crush")
                self.assertEqual(
                    player.max_hit, setup["expected_max_hit"],
                    rf"\n setup={setup['name']!r}"
                    rf"\n expected_max_hit={setup['expected_max_hit']}"
                    rf"\n actual_max_hit={{player.max_hit}}"
                )
            return test

        TestCls = type(class_name, (unittest.TestCase,), {
            "test_accuracy_roll": build_accuracy_test(setup),
            "test_max_hit":      build_max_hit_test(setup),
        })
        globals()[class_name] = TestCls


def _build_player_from_setup(setup):
    player = Loadout(gear_names=setup["gear_names"]).build()

    weapon = WeaponRegistry.get(setup["weapon"])
    player.equip_weapon(weapon)

    if "attack_style_override" in setup:
        player.weapon.attack_style = setup["attack_style_override"]

    if "prayer" in setup:
        player.prayer = PrayerRegistry.get(setup["prayer"])

    if "boosts" in setup:
        player.boosts = [PotionRegistry.get(b) for b in setup["boosts"]]

    return player


_make_test_classes()


if __name__ == "__main__":
    unittest.main()
